// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleAppsScriptType
public import GoogleAppsScriptTypeCalendar
public import GoogleAppsScriptTypeDocs
public import GoogleAppsScriptTypeDrive
public import GoogleAppsScriptTypeGmail
public import GoogleAppsScriptTypeSheets
public import GoogleAppsScriptTypeSlides
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Google Workspace add-on configuration.
public struct AddOns: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Configuration that is common across all Google Workspace add-ons.
  public var common: GoogleAppsScriptType.CommonAddOnManifest? = nil

  /// Gmail add-on configuration.
  public var gmail: GoogleAppsScriptTypeGmail.GmailAddOnManifest? = nil

  /// Drive add-on configuration.
  public var drive: GoogleAppsScriptTypeDrive.DriveAddOnManifest? = nil

  /// Calendar add-on configuration.
  public var calendar: GoogleAppsScriptTypeCalendar.CalendarAddOnManifest? = nil

  /// Docs add-on configuration.
  public var docs: GoogleAppsScriptTypeDocs.DocsAddOnManifest? = nil

  /// Sheets add-on configuration.
  public var sheets: GoogleAppsScriptTypeSheets.SheetsAddOnManifest? = nil

  /// Slides add-on configuration.
  public var slides: GoogleAppsScriptTypeSlides.SlidesAddOnManifest? = nil

  /// Options for sending requests to add-on HTTP endpoints
  public var httpOptions: GoogleAppsScriptType.HttpOptions? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AddOns`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AddOns().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let common = CodingKeys(stringValue: "common")
    static let gmail = CodingKeys(stringValue: "gmail")
    static let drive = CodingKeys(stringValue: "drive")
    static let calendar = CodingKeys(stringValue: "calendar")
    static let docs = CodingKeys(stringValue: "docs")
    static let sheets = CodingKeys(stringValue: "sheets")
    static let slides = CodingKeys(stringValue: "slides")
    static let httpOptions = CodingKeys(stringValue: "httpOptions")

    static let _knownKeys: Set<Swift.String> = [
      "common",
      "gmail",
      "drive",
      "calendar",
      "docs",
      "sheets",
      "slides",
      "httpOptions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.common = try container.decodeIfPresent(
      GoogleAppsScriptType.CommonAddOnManifest.self, forKey: .common)
    self.gmail = try container.decodeIfPresent(
      GoogleAppsScriptTypeGmail.GmailAddOnManifest.self, forKey: .gmail)
    self.drive = try container.decodeIfPresent(
      GoogleAppsScriptTypeDrive.DriveAddOnManifest.self, forKey: .drive)
    self.calendar = try container.decodeIfPresent(
      GoogleAppsScriptTypeCalendar.CalendarAddOnManifest.self, forKey: .calendar)
    self.docs = try container.decodeIfPresent(
      GoogleAppsScriptTypeDocs.DocsAddOnManifest.self, forKey: .docs)
    self.sheets = try container.decodeIfPresent(
      GoogleAppsScriptTypeSheets.SheetsAddOnManifest.self, forKey: .sheets)
    self.slides = try container.decodeIfPresent(
      GoogleAppsScriptTypeSlides.SlidesAddOnManifest.self, forKey: .slides)
    self.httpOptions = try container.decodeIfPresent(
      GoogleAppsScriptType.HttpOptions.self, forKey: .httpOptions)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.common, forKey: .common)
    try container.encodeIfPresent(self.gmail, forKey: .gmail)
    try container.encodeIfPresent(self.drive, forKey: .drive)
    try container.encodeIfPresent(self.calendar, forKey: .calendar)
    try container.encodeIfPresent(self.docs, forKey: .docs)
    try container.encodeIfPresent(self.sheets, forKey: .sheets)
    try container.encodeIfPresent(self.slides, forKey: .slides)
    try container.encodeIfPresent(self.httpOptions, forKey: .httpOptions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gsuiteaddons.v1.AddOns"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
