// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// A service for managing Google Workspace add-ons deployments.
///
/// A Google Workspace add-on is a third-party embedded component that can be
/// installed in Google Workspace Applications like Gmail, Calendar, Drive, and
/// the Google Docs, Sheets, and Slides editors. Google Workspace add-ons can
/// display UI cards, receive contextual information from the host application,
/// and perform actions in the host application (See:
/// https://developers.google.com/gsuite/add-ons/overview for more information).
///
/// A Google Workspace add-on deployment resource specifies metadata about the
/// add-on, including a specification of the entry points in the host application
/// that trigger add-on executions (see:
/// https://developers.google.com/gsuite/add-ons/concepts/gsuite-manifests).
/// Add-on deployments defined via the Google Workspace add-ons API define their
/// entrypoints using HTTPS URLs (See:
/// https://developers.google.com/gsuite/add-ons/guides/alternate-runtimes),
///
/// A Google Workspace add-on deployment can be installed in developer mode,
/// which allows an add-on developer to test the experience an end-user would see
/// when installing and running the add-on in their G Suite applications.  When
/// running in developer mode, more detailed error messages are exposed in the
/// add-on UI to aid in debugging.
///
/// A Google Workspace add-on deployment can be published to Google Workspace
/// Marketplace, which allows other Google Workspace users to discover and
/// install the add-on.  See:
/// https://developers.google.com/gsuite/add-ons/how-tos/publish-add-on-overview
/// for details.
///
/// @Snippet(path: "GSuiteAddOnsQuickstart")
public final class GSuiteAddOnsClient: Clients.GSuiteAddOnsProtocol, Sendable {
  let inner: any Clients.GSuiteAddOnsStub

  /// Creates a new `GSuiteAddOnsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.GSuiteAddOnsStub = try Clients.GSuiteAddOnsTransport(options)
    inner = Clients.GSuiteAddOnsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.GSuiteAddOnsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets the authorization information for deployments in a given project.
  ///
  /// @Snippet(path: "GSuiteAddOns_GetAuthorization")
  public func getAuthorization(
    request: GetAuthorizationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization {
    try await self.inner.getAuthorization(request: request, options: options)
  }

  /// Creates a deployment with the specified name and configuration.
  ///
  /// @Snippet(path: "GSuiteAddOns_CreateDeployment")
  public func createDeployment(
    request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    try await self.inner.createDeployment(request: request, options: options)
  }

  /// Creates or replaces a deployment with the specified name.
  ///
  /// @Snippet(path: "GSuiteAddOns_ReplaceDeployment")
  public func replaceDeployment(
    request: ReplaceDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    try await self.inner.replaceDeployment(request: request, options: options)
  }

  /// Gets the deployment with the specified name.
  ///
  /// @Snippet(path: "GSuiteAddOns_GetDeployment")
  public func getDeployment(
    request: GetDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    try await self.inner.getDeployment(request: request, options: options)
  }

  /// Lists all deployments in a particular project.
  ///
  /// @Snippet(path: "GSuiteAddOns_ListDeployments")
  public func listDeployments(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse {
    try await self.inner.listDeployments(request: request, options: options)
  }

  /// Deletes the deployment with the given name.
  ///
  /// @Snippet(path: "GSuiteAddOns_DeleteDeployment")
  public func deleteDeployment(
    request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDeployment(request: request, options: options)
  }

  /// Installs a deployment in developer mode.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @Snippet(path: "GSuiteAddOns_InstallDeployment")
  public func installDeployment(
    request: InstallDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.installDeployment(request: request, options: options)
  }

  /// Uninstalls a developer mode deployment.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @Snippet(path: "GSuiteAddOns_UninstallDeployment")
  public func uninstallDeployment(
    request: UninstallDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.uninstallDeployment(request: request, options: options)
  }

  /// Fetches the install status of a developer mode deployment.
  ///
  /// @Snippet(path: "GSuiteAddOns_GetInstallStatus")
  public func getInstallStatus(
    request: GetInstallStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus {
    try await self.inner.getInstallStatus(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `GSuiteAddOnsClient`.
  ///
  /// To mock `GSuiteAddOnsClient` change your functions to receive
  /// `some GSuiteAddOnsProtocol` or `any GSuiteAddOnsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol GSuiteAddOnsProtocol: Sendable {
    /// See `GSuiteAddOnsClient.getAuthorization`.
    func getAuthorization(
      request: GetAuthorizationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization

    /// See `GSuiteAddOnsClient.createDeployment`.
    func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    /// See `GSuiteAddOnsClient.replaceDeployment`.
    func replaceDeployment(
      request: ReplaceDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    /// See `GSuiteAddOnsClient.getDeployment`.
    func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    /// See `GSuiteAddOnsClient.listDeployments`.
    func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse

    /// See `GSuiteAddOnsClient.deleteDeployment`.
    func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `GSuiteAddOnsClient.installDeployment`.
    func installDeployment(
      request: InstallDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `GSuiteAddOnsClient.uninstallDeployment`.
    func uninstallDeployment(
      request: UninstallDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `GSuiteAddOnsClient.getInstallStatus`.
    func getInstallStatus(
      request: GetInstallStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus
  }
}

// Default implementations
extension Clients.GSuiteAddOnsProtocol {
  public func getAuthorization(request: GetAuthorizationRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.Authorization
  {
    try await self.getAuthorization(request: request, options: .init())
  }

  public func getAuthorization(
    request: GetAuthorizationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuthorization(
    name: Swift.String,
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization {
    let request = GetAuthorizationRequest().with {
      $0.name = name
    }
    return try await self.getAuthorization(request: request)
  }

  public func createDeployment(request: CreateDeploymentRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.Deployment
  {
    try await self.createDeployment(request: request, options: .init())
  }

  public func createDeployment(
    request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDeployment(
    parent: Swift.String,
    deployment: Deployment?,
    deploymentId: Swift.String,
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    let request = CreateDeploymentRequest().with {
      $0.parent = parent
      $0.deployment = deployment
      $0.deploymentId = deploymentId
    }
    return try await self.createDeployment(request: request)
  }

  public func replaceDeployment(request: ReplaceDeploymentRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.Deployment
  {
    try await self.replaceDeployment(request: request, options: .init())
  }

  public func replaceDeployment(
    request: ReplaceDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func replaceDeployment(
    deployment: Deployment?,
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    let request = ReplaceDeploymentRequest().with {
      $0.deployment = deployment
    }
    return try await self.replaceDeployment(request: request)
  }

  public func getDeployment(request: GetDeploymentRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.Deployment
  {
    try await self.getDeployment(request: request, options: .init())
  }

  public func getDeployment(
    request: GetDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
    let request = GetDeploymentRequest().with {
      $0.name = name
    }
    return try await self.getDeployment(request: request)
  }

  public func listDeployments(request: ListDeploymentsRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse
  {
    try await self.listDeployments(request: request, options: .init())
  }

  public func listDeployments(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDeploymentsByItems(
    request: ListDeploymentsRequest
  ) -> any AsyncSequence<Deployment, Swift.Error> {
    self.listDeploymentsByItems(request: request, options: .init())
  }

  /// Lists all deployments in a particular project.
  ///
  /// @Snippet(path: "GSuiteAddOns_ListDeployments")
  public func listDeploymentsByItems(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Deployment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listDeployments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDeploymentsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Deployment, Swift.Error> {
    let request = ListDeploymentsRequest().with {
      $0.parent = parent
    }
    return self.listDeploymentsByItems(request: request)
  }

  public func deleteDeployment(request: DeleteDeploymentRequest) async throws {
    try await self.deleteDeployment(request: request, options: .init())
  }

  public func deleteDeployment(
    request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDeployment(
    name: Swift.String,
  ) async throws {
    let request = DeleteDeploymentRequest().with {
      $0.name = name
    }
    try await self.deleteDeployment(request: request)
  }

  public func installDeployment(request: InstallDeploymentRequest) async throws {
    try await self.installDeployment(request: request, options: .init())
  }

  public func installDeployment(
    request: InstallDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func installDeployment(
    name: Swift.String,
  ) async throws {
    let request = InstallDeploymentRequest().with {
      $0.name = name
    }
    try await self.installDeployment(request: request)
  }

  public func uninstallDeployment(request: UninstallDeploymentRequest) async throws {
    try await self.uninstallDeployment(request: request, options: .init())
  }

  public func uninstallDeployment(
    request: UninstallDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func uninstallDeployment(
    name: Swift.String,
  ) async throws {
    let request = UninstallDeploymentRequest().with {
      $0.name = name
    }
    try await self.uninstallDeployment(request: request)
  }

  public func getInstallStatus(request: GetInstallStatusRequest) async throws
    -> GoogleCloudGSuiteAddOnsV1.InstallStatus
  {
    try await self.getInstallStatus(request: request, options: .init())
  }

  public func getInstallStatus(
    request: GetInstallStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstallStatus(
    name: Swift.String,
  ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus {
    let request = GetInstallStatusRequest().with {
      $0.name = name
    }
    return try await self.getInstallStatus(request: request)
  }
}
